services:
  strapi:
    build: .
    container_name: storify-backend
    env_file:
      - .env
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: false
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./public/uploads:/app/public/uploads # Host-to-container mount for uploads
      - strapi_uploads:/app/public/uploads   # Named volume for uploads persistence
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: storify-db
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - strapi_db_data:/var/lib/postgresql/data # Persistent database data
    restart: always

volumes:
  strapi_db_data: # For database persistence
  strapi_uploads: # For image uploads persistence
