name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Trigger on push to main branch (adjust as needed)
      
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t vivinkv/storify:latest .
          
      - name: Push Docker Image
        run: |
          docker push vivinkv/storify:latest
