name: Build and Deploy Docker Image to Render

on:
  push:
    branches:
      - master  # Trigger this workflow when changes are pushed to the 'master' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build and Push Docker Image
        id: build
        run: |
          # Get commit SHA and use it as a dynamic tag
          COMMIT_SHA=$(git rev-parse --short HEAD)
          IMAGE_NAME="vivinkv/storify"

          # Build Docker image with both latest and commit SHA tags
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$COMMIT_SHA .

          # Push both tags to Docker Hub
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$COMMIT_SHA

          # Set image tags as outputs for reference
          echo "IMAGE_TAG_LATEST=$IMAGE_NAME:latest" >> $GITHUB_ENV
          echo "IMAGE_TAG_COMMIT=$IMAGE_NAME:$COMMIT_SHA" >> $GITHUB_ENV

      - name: Trigger Render Deploy (via Deploy Hook)
        run: |
          # Use Render deploy hook to trigger redeployment
          curl -X POST "https://api.render.com/deploy/srv-cufpp52j1k6c73ft2da0?key=X7psl2t_UI8"
