name: Build and Deploy Docker Images to Render

on:
  push:
    branches:
      - master  # Trigger this workflow when changes are pushed to the 'master' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build and Push storify-strapi Image
        id: build_strapi
        run: |
          # Get commit SHA and use it as a dynamic tag
          COMMIT_SHA=$(git rev-parse --short HEAD)
          STRAPI_IMAGE_NAME="vivinkv/storify-strapi"

          # Build Docker image for storify-strapi
          docker build -t $STRAPI_IMAGE_NAME:latest -t $STRAPI_IMAGE_NAME:$COMMIT_SHA .

          # Push Strapi image tags to Docker Hub
          docker push $STRAPI_IMAGE_NAME:latest
          docker push $STRAPI_IMAGE_NAME:$COMMIT_SHA

      - name: Build and Push postgres Image
        id: build_postgres
        run: |
          POSTGRES_IMAGE_NAME="vivinkv/postgres"

          # Pull the postgres:16 base image and tag it
          docker pull postgres:16
          docker tag postgres:16 $POSTGRES_IMAGE_NAME:latest

          # Push the Postgres image tag to Docker Hub
          docker push $POSTGRES_IMAGE_NAME:latest

      - name: Deploy using Docker Compose
        run: |
          # Ensure services are started with the correct images and volumes
          docker-compose -f docker-compose.yml up -d

      - name: Trigger Render Deploy (via Deploy Hook)
        run: |
          # Use Render deploy hook to trigger redeployment
          curl -X POST "https://api.render.com/deploy/srv-cufpp52j1k6c73ft2da0?key=X7psl2t_UI8"
