name: Build and Deploy Docker Image to Render

on:
  push:
    branches:
      - master  # Trigger this workflow when changes are pushed to the 'master' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_USER_PASSWORD }}

      - name: Build and Push Docker Image (Latest Tag)
        id: build
        run: |
          # Build Docker image with 'latest' tag
          IMAGE_TAG="vivinkv/storify:latest"
          
          # Build the Docker image
          docker build -t $IMAGE_TAG .
          
          # Push image to Docker Hub
          docker push $IMAGE_TAG
          
          # Set the image tag as an environment variable
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Trigger Render Deploy (via Deploy Hook)
        run: |
          # Trigger redeployment using Render Deploy Hook
          curl -X POST https://render.com/deploy/hooks/${{ secrets.RENDER_DEPLOY_HOOK_URL }}
